# Generated by Django 5.0.2 on 2024-02-26 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0004_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
