# Generated by Django 5.0.2 on 2024-05-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0010_alter_commande_totalcde'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='totalCde',
            field=models.FloatField(default=0.0, editable=False),
        ),
    ]
